#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon May 18 09:43:57 2009

import wx
from PostProcess import PostProcess

class PostGUI(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        pp = PostProcess(None, -1, "")
        self.SetTopWindow(pp)
        pp.Show()
        return 1

# end of class SimulatorGUI

if __name__ == "__main__":
    PostGUI = PostGUI(0)
    PostGUI.MainLoop()
