pyrcc5 ../images/images.qrc -o images_rc.py
pyuic5 ../windows/ICESymMainWindow.ui -o ICESymMainWindow_ui.py
sed -i "/\b\(setContentsMargins\)\b/d" ICESymMainWindow_ui.py
pyuic5 ../windows/ConfigurationWidget.ui -o configurationWidget_ui.py
sed -i "/\b\(setContentsMargins\)\b/d" configurationWidget_ui.py
pyuic5 ../windows/ValveDialog.ui -o valveDialog_ui.py
sed -i "/\b\(setContentsMargins\)\b/d" valveDialog_ui.py
pyuic5 ../windows/AtmosphereDialog.ui -o atmosphereDialog_ui.py
sed -i "/\b\(setContentsMargins\)\b/d" atmosphereDialog_ui.py
pyuic5 ../windows/TubeDialog.ui -o tubeDialog_ui.py
sed -i "/\b\(setContentsMargins\)\b/d" tubeDialog_ui.py
pyuic5 ../windows/InputDialog.ui -o inputDialog_ui.py
sed -i "/\b\(setContentsMargins\)\b/d" inputDialog_ui.py
pyuic5 ../windows/CylinderDialog.ui -o cylinderDialog_ui.py
sed -i "/\b\(setContentsMargins\)\b/d" cylinderDialog_ui.py
pyuic5 ../windows/TankDialog.ui -o tankDialog_ui.py
sed -i "/\b\(setContentsMargins\)\b/d" tankDialog_ui.py
pyuic5 ../windows/JunctionDialog.ui -o junctionDialog_ui.py
sed -i "/\b\(setContentsMargins\)\b/d" junctionDialog_ui.py
pyuic5 ../windows/LogTabWidget.ui -o logTabWidget_ui.py
sed -i "/\b\(setContentsMargins\)\b/d" logTabWidget_ui.py
pyuic5 ../windows/PostProcessWidget.ui -o postProcessWidget_ui.py
sed -i "/\b\(setContentsMargins\)\b/d" postProcessWidget_ui.py
pyuic5 ../windows/PlotTypeOneWidget.ui -o plotTypeOneWidget_ui.py
sed -i "/\b\(setContentsMargins\)\b/d" plotTypeOneWidget_ui.py
pyuic5 ../windows/PlotTypeTwoWidget.ui -o plotTypeTwoWidget_ui.py
sed -i "/\b\(setContentsMargins\)\b/d" plotTypeTwoWidget_ui.py
pyuic5 ../windows/PlotTypeThreeWidget.ui -o plotTypeThreeWidget_ui.py
sed -i "/\b\(setContentsMargins\)\b/d" plotTypeThreeWidget_ui.py
pyuic5 ../windows/NewCaseDialog.ui -o newCaseDialog_ui.py
sed -i "/\b\(setContentsMargins\)\b/d" newCaseDialog_ui.py